name: nginx-server
services:
  nginx:
    image: funnyzak/nginx:latest
    container_name: app-nginx
    restart: on-failure
    ports:
      - 1000:80
      - 1001:81
    volumes:
      - ../conf/nginx.conf:/etc/nginx/nginx.conf
      - ../conf/conf.d/:/etc/nginx/conf.d/
      - ~/Desktop:/mnt/desk
