name: Check Dockerfile Changes

on:
  push:
    paths:
      - '**/Dockerfile'

jobs:
  check_dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          files: '**/Dockerfile'

      - id: set-matrix
        run: |
          DOCKERFILES=$(echo '${{ steps.changed-files.outputs.all_changed_files }}' | jq -R -s 'split("\n") | map(select(length>0)) | {dockerfile: .}' | jq -c .)
          echo "matrix=$DOCKERFILES" >> $GITHUB_OUTPUT

  run_docker_build:
    needs: check_dockerfiles
    if: ${{ fromJson(needs.check_dockerfiles.outputs.matrix).dockerfile[0] }}
    strategy:
      matrix: ${{fromJson(needs.check_dockerfiles.outputs.matrix)}}
    uses: funnyzak/image-publish/.github/workflows/image_publish.yml@main
    with:
      docker_context: ${{ github.workspace }}/${{ dirname(matrix.dockerfile) }}
      tag: nightly

  log_results:
    needs: run_docker_build
    runs-on: ubuntu-latest
    steps:
      - name: Log Build Results
        run: |
          if [[ ${{ needs.run_docker_build.result }} == 'success' ]]; then
            echo "Docker builds completed successfully."
          else
            echo "Some Docker builds failed. Please check the logs for more information."
          fi
