name: Check Dockerfile Changes

on:
  push:
    paths:
      - '**/Dockerfile'


permissions:
  contents: write
  packages: write


jobs:
  check_dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          files: '**/Dockerfile'

      - name: Set matrix
        id: set-matrix
        run: |
          echo "All changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          CONTEXTS=$(echo '${{ steps.changed-files.outputs.all_changed_files }}' | jq -R -s 'split(" ") | map(select(length>0)) | {dockerfile_context: map(sub("/[^/]+$"; ""))}' | jq -c .)
          echo "List of Dockerfile contexts: $CONTEXTS"
          echo "matrix=$CONTEXTS" >> $GITHUB_OUTPUT

  run_docker_build:
    needs: check_dockerfiles
    if: ${{ fromJson(needs.check_dockerfiles.outputs.matrix).dockerfile_context.length }} > 0
    strategy:
      matrix: ${{ fromJson(needs.check_dockerfiles.outputs.matrix) }}
    uses: ./.github/workflows/image_publish.yml
    with:
      build_context: ${{ matrix.dockerfile_context }}
      build_tag: nightly
      build_args: BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      build_platforms: linux/amd64,linux/arm64
    secrets: inherit